# Generated by Django 3.2.6 on 2021-09-11 10:27

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import stocksetfsbonds.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksETFsBonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Слаг')),
                ('icon', models.ImageField(blank=True, upload_to=stocksetfsbonds.utilities.security_img_directory_path, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип ценной бумаги',
                'verbose_name_plural': 'Типы ценных бумаг',
            },
        ),
        migrations.CreateModel(
            name='StockETFBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='ticker', unique=True, verbose_name='Слаг')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='Тикер')),
                ('icon', models.ImageField(blank=True, upload_to=stocksetfsbonds.utilities.security_img_directory_path, verbose_name='Логотип')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('stocketforbond', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksetfsbonds.stocksetfsbonds', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Ценная бумага',
                'verbose_name_plural': 'Ценные бумаги',
            },
        ),
    ]
